name: "test aqualab export"
description: ""
inputs:
  game:
   description: "The game with data to export."
   required: true
   default: 'Crystal'
  db:
    description: "game database"
    required: true
    default: ""
runs:
  using: "composite"
  steps:
    - name: Set up Python libraries
      run: |
        python3.8 -m pip install --upgrade pip
        python3.8 -m pip install setuptools --quiet
        python3.8 -m pip install wheel --quiet
        python3.8 -m pip install -r requirements.txt --quiet
      shell: bash
    - name: Set up code
      run: cp config/config.py.template config/config.py 
      shell: bash
    - name: Set database name
      run: sed -i 's/project_id.dataset_id/${{inputs.db}}/g' config/config.py
      shell: bash
    - name: Run export
      run: python3.8 main.py export AQUALAB 5/6/2021 6/6/2021
    - name: Upload zips as artifacts
      uses: actions/upload-artifact@v2
      with:
        path: ./data/AQUALAB/*.zip
