name: "test aqualab export"
description: ""
inputs:
  game:
   description: "The game with data to export."
   required: true
   default: 'Crystal'
runs:
  using: "composite"
  if: contains(${{ inputs.game }}, "AQUALAB")
  steps:
    - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.AQUALAB_GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
    - name: Set up Python libraries
      run: |
        python3.8 -m pip install --upgrade pip
        python3.8 -m pip install setuptools --quiet
        python3.8 -m pip install wheel --quiet
        python3.8 -m pip install -r requirements.txt --quiet
      shell: bash
    - name: Set up code
      run: cp config/config.py.template config/config.py 
      shell: bash
    - name: Set database name
      run: sed -i 's/project_id.dataset_id/${{secrets.AQUALAB_DB_NAME}}/g' config/config.py
      shell: bash
    - name: Run export
      run: python3.8 main.py export AQUALAB 5/6/2021 6/6/2021
    - name: Upload zips as artifacts
      uses: actions/upload-artifact@v2
      with:
        path: ./data/AQUALAB/*.zip
