name: Aqualab BigQuery Test
on:
  push:
  workflow_dispatch:
jobs:
  test_connect:
    runs-on: ubuntu-18.04
    steps:
    - name: Set up Cloud SDK
      uses: actions/checkout@v2
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    - name: Get correct Python
      run: |
        sudo apt-get -q install python3.8
        sudo apt-get -q install python3.8-dev
    - uses: actions/checkout@v2
    - name: Set up Python libraries
      run: |
        python3.8 -m pip install --upgrade pip
        python3.8 -m pip install setuptools --quiet
        python3.8 -m pip install wheel --quiet
        python3.8 -m pip install -r requirements.txt --quiet
      shell: bash
    - name: Set up code
      run: cp config/config.py.template config/config.py 
      shell: bash
    - name: Set database name
      run: sed -i 's/project_id.dataset_id/${{secrets.AQUALAB_DB_NAME}}/g' config/config.py
      shell: bash
    - name: Run export
      run: python3.8 main.py export AQUALAB 6/8/2021 6/9/2021
    - name: Upload zips as artifacts
      uses: actions/upload-artifact@v2
      with:
        path: ./data/AQUALAB/*.zip
